//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        public int id_pelicula { get; set; }
        public string nombre_pelicula { get; set; }
        public string año_pelicula { get; set; }
        public string duracion_pelicula { get; set; }
        public string pais_pelicula { get; set; }
        public string direccion_pelicula { get; set; }
        public string reparto_pelicula { get; set; }
        public string productora_pelicula { get; set; }
        public string genero_pelicula { get; set; }
        public string tamaño_pelicula { get; set; }
        public string formato_pelicula { get; set; }
        public string idioma_principal { get; set; }
        public string idioma_secundario { get; set; }
        public string resolucion_pelicula { get; set; }
        public string subtitulos_pelicula { get; set; }
    }
}
