//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventario_PeliculasEntities : DbContext
    {
        public Inventario_PeliculasEntities()
            : base("name=Inventario_PeliculasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<pelicula> pelicula { get; set; }
        public virtual DbSet<serie> serie { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }

        public System.Data.Entity.DbSet<Peliculas.Models.ElUsuario> ElUsuarios { get; set; }
    }
}
