//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie
    {
        public int id_serie { get; set; }
        public string nombre_serie { get; set; }
        public string año_serie { get; set; }
        public string duracion_serie { get; set; }
        public string pais_serie { get; set; }
        public string direccion_serie { get; set; }
        public string reparto_serie { get; set; }
        public string productora_serie { get; set; }
        public string genero_serie { get; set; }
        public string tamaño_serie { get; set; }
        public string formato_serie { get; set; }
        public string idioma_principal { get; set; }
        public string idioma_secundario { get; set; }
        public string resolucion_serie { get; set; }
        public string subtitulos_serie { get; set; }
    }
}
